// <auto-generated />
using System;
using CursoIdiomas.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CursoIdiomas.API.Migrations
{
    [DbContext(typeof(CursoIdiomasContext))]
    partial class CursoIdiomasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CursoIdiomas.API.Infrastructure.Persistence.Models.AlunoModel", b =>
                {
                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimeiroNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricula");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("CursoIdiomas.API.Infrastructure.Persistence.Models.AlunoTurmaModel", b =>
                {
                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Matricula", "Numero");

                    b.HasIndex("Numero");

                    b.ToTable("AlunoTurma");
                });

            modelBuilder.Entity("CursoIdiomas.API.Infrastructure.Persistence.Models.IdiomaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Idioma");
                });

            modelBuilder.Entity("CursoIdiomas.API.Infrastructure.Persistence.Models.TurmaModel", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdIdioma")
                        .HasColumnType("int");

                    b.HasKey("Numero");

                    b.HasIndex("IdIdioma");

                    b.ToTable("Turma");
                });

            modelBuilder.Entity("CursoIdiomas.API.Infrastructure.Persistence.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HashSenha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CursoIdiomas.API.Infrastructure.Persistence.Models.AlunoTurmaModel", b =>
                {
                    b.HasOne("CursoIdiomas.API.Infrastructure.Persistence.Models.AlunoModel", "Aluno")
                        .WithMany("Turmas")
                        .HasForeignKey("Matricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CursoIdiomas.API.Infrastructure.Persistence.Models.TurmaModel", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("Numero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("CursoIdiomas.API.Infrastructure.Persistence.Models.TurmaModel", b =>
                {
                    b.HasOne("CursoIdiomas.API.Infrastructure.Persistence.Models.IdiomaModel", "Idioma")
                        .WithMany()
                        .HasForeignKey("IdIdioma");

                    b.Navigation("Idioma");
                });

            modelBuilder.Entity("CursoIdiomas.API.Infrastructure.Persistence.Models.AlunoModel", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("CursoIdiomas.API.Infrastructure.Persistence.Models.TurmaModel", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
